### PR TITLE
changes to Ayurvedasutram

### PR DESCRIPTION
**Pull request by wujastyk**
I have added info to the header of the Ayurvedasutram.xml

### CODE REVIEW

**Comment by paddymcall** [comment]
Thanks Dominik, could you please issue this pull request against the `devel' branch instead?

Also, a few requests:

1. Could you please delete either the IAST or the devanāgarī version of the Mbh?  Or is there a good reason to duplicate the file in the library?
1. Could you please also add the new attributes etc. to the odd file?  The rnc file will otherwise be overwritten the next time we generate it from the odd file  (I should write a  test to make sure this doesn't slip through).

**Comment by paddymcall** [comment]
Dear Dominik, please issue this pull request against the devel branch (https://github.com/sarit/SARIT-corpus/tree/devel).

**Comment by wujastyk** [comment]
Is everything now done?
When I try to pull my master into the SARIT-corpus devel branch, Github
tells me there's nothing to do.

[image: Screenshot from 2018-11-02 18-52-36.png]

I don't use Github enough to feel confident that I'm doing the right things
always :-(
It looks to me as if the IAST Mbh got successfully removed from devel in
change #95

Best,
Dominik

**Comment by paddymcall** [comment]
Yes, your changes have been merged into the devel branch, that's why ``there's nothing to do''.  The merge was done here: https://github.com/sarit/SARIT-corpus/commit/aa117a79869ecf3952f659f2fc6b695120c04d87

**Pull request closed without merging**
