### PR TITLE
added ref's, trailer, and ed- and xml:lang-attributes to naradasmriti; ; added to content to empty ref's in vadanyayatika

### PR DESCRIPTION
**Pull request by lolalde**

### CODE REVIEW

**Comment by lolalde** [comment]
I've added two new files: avayavinirakarana.xml and samanyadusana.xml

**Comment by wujastyk** [comment]
Great news!

--

**Comment by lolalde** [comment]
I've added another new file: pramanantarbhava.xml and fixed the problem with the file name.

**Comment by wujastyk** [comment]
sorry to appear dim, but where are pramanantarbhava.xml and the other
recently-added files?  I don't see them at

   - sarit.indology.info or at
   - showcases.exist-db.org/exist/apps/sarit-pm/works/?start=1 or
   - http://kjc-sv016.kjc.uni-heidelberg.de:8090/

I see the file at Github in sarit corpus.  What is the mechanism for
getting the file from Github to the exist db display?  It used to be done
manually by Paddy. Is it stil a manual process?  If so, do we want to think
about creating a Git->Exist pathway that isn't manual?

Best,
Dominik


--
Professor Dominik Wujastyk* <http://ualberta.Academia.edu/DominikWujastyk>
Singhmar Chair in Classical Indian Society and Polity
Department of History and Classics <http://historyandclassics.ualberta.ca/>
University of Alberta, Canada

**Comment by lolalde** [comment]
Yes, the data collection on exist-db is updated manually. I've updated it some minutes ago and have also asked Wolfgang to update it in the Showcase. The next meeting would be a good opportunity to discuss your suggestion about an automatic update.

**Pull request merged**
